version: '2.2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    container_name: kibana73
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
